### ISSUE TITLE
Support for `__aarch64__` flag

### ISSUE THREAD

**Issue by lmtr0** [tpoechtrager/osxcross#333]
As pointed out in https://github.com/briansmith/ring/issues/1442 it appears that the o64h-clang is not setting any arm flags:

**Comment by tpoechtrager** [comment]
OS? Clang compiler version?

**Comment by lmtr0** [comment]
Well clang was 13 and the os i tested was arch Linux container but it also doesn't work in Ubuntu, Manjaro and fedora with MacOS SDK 11.3

**Comment by lmtr0** [comment]
I was compiling a project in rust that had dependency in ring which is the crate broke the build. Btw starting the compilation with system clang fails but then switching to osxcross then works

**Comment by JimChenWYU** [comment]
how about it? I met the same error, can not compile briansmith/ring

**Comment by lmtr0** [comment]
use -D__aarch64__

**Comment by lmtr0** [comment]
in `.cargo/config.toml`:
```toml
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-D__aarch64__"]
linker = "o64h-clang"
ar = "aarch64-apple-darwin20.4-ar"
```

**Comment by JimChenWYU** [comment]
@lmtr0 got same error
I had run `cargo clean`

.cargo/config.toml
```toml
[build]
target = "aarch64-apple-darwin"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-D__aarch64__"]
linker = "/osxcross/bin/aarch64-apple-darwin20.4-clang"
ar = "/osxcross/bin/aarch64-apple-darwin20.4-ar"
```

`o64h-clang` I found it is same as `/osxcross/bin/aarch64-apple-darwin20.4-clang`
