### ISSUE TITLE
MacPorts "no suitable version found for darwin_17" even though my target is darwin 23

### ISSUE THREAD

**Issue by Frityet** [tpoechtrager/osxcross#451]
```sh
 % omp install shared-mime-info
searching package shared-mime-info ...
no suitable version found for darwin_17
trying shared-mime instead ...
searching package shared-mime ...
no package found
trying shared instead ...
searching package shared ...
no package found
failed to install shared, try with '-v'
use 'omp fake-install <pkgname>' to fake install non-existing packages
```

`sw_vers`:
```yaml
ProductName:    Mac OS X
ProductVersion: 10.13
BuildVersion:   0CFFFF
```
